[build]
  publish = "public"
  command = "# no build command"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.com/api/:splat"
  status = 200
  force = true

[functions]
  directory = "functions" 